//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t __deregister_frame_info2(int32_t * a1);
int32_t __register_frame_info2(int32_t * a1, int32_t * a2);
int32_t _fini(void);
int32_t _ftext(void);
int32_t _init(void);
int32_t function_40063c(void);
int32_t function_400648(void);
int32_t function_400660(int32_t a1, int32_t a2);
int32_t function_400694(int32_t a1);
int32_t function_4007bc(void);
int32_t function_4007f0(int32_t * str);
int32_t function_4009a8(void);
int32_t function_400b00(void);
int32_t function_400b58(void);
int32_t function_400b64(int32_t a1, int32_t a2);
int32_t function_400c20(char * format, ...);
int32_t function_400c40(char * s);
int32_t function_400c60(char * s1, char * s2, int32_t n);
int32_t function_400c70(char * format, ...);
void function_400c80(struct _IO_FILE * stream, char * buf);
int32_t function_400c90(int32_t main, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_400ca0(char * s);

// --------------------- Global Variables ---------------------

int32_t g1 = -0x5be902ae; // 0x400b98
int32_t g2 = 0; // 0x400bf0
int32_t g3 = -1; // 0x410cb0
int32_t g4 = -1; // 0x410cb8
int32_t g5 = 0; // 0x410cbc
struct _IO_FILE * g6 = NULL; // 0x410cc0
struct _IO_FILE * g7 = NULL; // 0x410cc4
char (*g8)[6] = "Q|j{g"; // 0x410d00
char g10 = 0; // 0x410d30
int32_t g11 = 0; // 0x410d34
int32_t g12 = 0; // 0x410d38
int32_t g13;
int32_t * g9 = &g1; // 0x410d04

// ------------------------ Functions -------------------------

// Address range: 0x400634 - 0x40063c
int32_t _init(void) {
    // 0x400634
    int32_t result; // 0x400634
    return result;
}

// Address range: 0x40063c - 0x400648
int32_t function_40063c(void) {
    // 0x40063c
    return function_400648();
}

// Address range: 0x400648 - 0x400660
int32_t function_400648(void) {
    // 0x400648
    function_4007bc();
    return function_400660((int32_t)&g13, (int32_t)&g13);
}

// Address range: 0x400660 - 0x400680
int32_t function_400660(int32_t a1, int32_t a2) {
    // 0x400660
    return function_400b00();
}

// Address range: 0x400680 - 0x400688
int32_t _ftext(void) {
    // 0x400680
    return function_400694((int32_t)&g13);
}

// Address range: 0x400694 - 0x4007bc
int32_t function_400694(int32_t a1) {
    // 0x400694
    int32_t v1; // 0x400694
    __libc_start_main(0x4009a8, a1, (char **)&v1, (void (*)())0x400634, (void (*)())0x400b50, NULL);
    unsigned char result = g10; // 0x400710
    if (result != 0) {
        // 0x400780
        return result;
    }
    // 0x400724
    if (g11 < ((int32_t)&g5 - (int32_t)&g4 >> 2) - 1) {
        // 0x40079c
        g11 = ((int32_t)&g5 - (int32_t)&g4 >> 2) - 1;
    }
    // 0x40075c
    __deregister_frame_info2(&g2);
    g10 = 1;
    // 0x400780
    return 1;
}

// Address range: 0x4007bc - 0x4007e4
int32_t function_4007bc(void) {
    // 0x4007bc
    return __register_frame_info2(&g2, &g12);
}

// Address range: 0x4007f0 - 0x4009a8
int32_t function_4007f0(int32_t * str) {
    int32_t v1 = (int32_t)str;
    int32_t v2 = 5; // 0x400930
    if (strlen((char *)str) > 5) {
        char * v3 = (char *)(v2 + v1);
        unsigned char v4 = *v3;
        char v5; // 0x4007f0
        if (v2 % 2 == 0) {
            // 0x400898
            v5 = (0x1000000 * (int32_t)(v4 / 64) | 0x4000000 * (int32_t)v4) / 0x1000000;
        } else {
            // 0x400828
            v5 = (0x1000000 * (int32_t)(v4 / 4) | 0x40000000 * (int32_t)v4) / 0x1000000;
        }
        // 0x400900
        *v3 = v5;
        v2++;
        while (v2 < strlen((char *)str)) {
            // 0x400814
            v3 = (char *)(v2 + v1);
            v4 = *v3;
            if (v2 % 2 == 0) {
                // 0x400898
                v5 = (0x1000000 * (int32_t)(v4 / 64) | 0x4000000 * (int32_t)v4) / 0x1000000;
            } else {
                // 0x400828
                v5 = (0x1000000 * (int32_t)(v4 / 4) | 0x40000000 * (int32_t)v4) / 0x1000000;
            }
            // 0x400900
            *v3 = v5;
            v2++;
        }
    }
    // 0x400934
    int32_t puts_rc; // 0x4007f0
    if (strncmp((char *)(v1 + 5), (char *)g9, 27) == 0) {
        // 0x400964
        puts_rc = puts("Right!");
    } else {
        // 0x40097c
        puts_rc = puts("Wrong!");
    }
    // 0x40098c
    return puts_rc;
}

// Address range: 0x4009a8 - 0x400af8
int32_t function_4009a8(void) {
    // 0x4009a8
    setbuf(g6, NULL);
    setbuf(g7, NULL);
    printf("Give me your flag:");
    int32_t str; // bp-44, 0x4009a8
    scanf("%32s", &str);
    int32_t v1 = 0;
    int32_t v2 = 0; // 0x400a70
    char * v3 = (char *)((int32_t)&v1 + 4 + v2); // 0x400a28
    *v3 = (char)((0x1000000 * (int32_t)*v3 ^ 0x20000000 - 0x1000000 * v2) / 0x1000000);
    v2 = v1 + 1;
    v1 = v2;
    while (v2 < 32) {
        // 0x400a1c
        v3 = (char *)((int32_t)&v1 + 4 + v2);
        *v3 = (char)((0x1000000 * (int32_t)*v3 ^ 0x20000000 - 0x1000000 * v2) / 0x1000000);
        v2 = v1 + 1;
        v1 = v2;
    }
    // 0x400a8c
    int32_t puts_rc; // 0x4009a8
    if (strncmp((char *)&str, g8, 5) == 0) {
        // 0x400ab4
        puts_rc = function_4007f0(&str);
    } else {
        // 0x400acc
        puts_rc = puts("Wrong");
    }
    // 0x400adc
    return puts_rc;
}

// Address range: 0x400b00 - 0x400b48
int32_t function_400b00(void) {
    // 0x400b00
    int32_t result; // 0x400b00
    if (g3 == -1) {
        // 0x400b28
        return result;
    }
    int32_t v1 = &g3; // 0x400b24
    while (*(int32_t *)(v1 - 4) != -1) {
        // 0x400b38
        v1 -= 4;
    }
    // 0x400b28
    return result;
}

// Address range: 0x400b50 - 0x400b58
int32_t _fini(void) {
    // 0x400b50
    int32_t result; // 0x400b50
    return result;
}

// Address range: 0x400b58 - 0x400b64
int32_t function_400b58(void) {
    // 0x400b58
    int32_t v1; // 0x400b58
    return function_400b64(v1, (int32_t)&g13);
}

// Address range: 0x400b64 - 0x400b84
int32_t function_400b64(int32_t a1, int32_t a2) {
    // 0x400b64
    int32_t result; // 0x400b64
    return result;
}

// Address range: 0x400c20 - 0x400c30
int32_t function_400c20(char * format, ...) {
    // 0x400c20
    return printf(format);
}

// Address range: 0x400c30 - 0x400c40
int32_t __register_frame_info2(int32_t * a1, int32_t * a2) {
    // 0x400c30
    return __register_frame_info();
}

// Address range: 0x400c40 - 0x400c50
int32_t function_400c40(char * s) {
    // 0x400c40
    return puts(s);
}

// Address range: 0x400c50 - 0x400c60
int32_t __deregister_frame_info2(int32_t * a1) {
    // 0x400c50
    return __deregister_frame_info();
}

// Address range: 0x400c60 - 0x400c70
int32_t function_400c60(char * s1, char * s2, int32_t n) {
    // 0x400c60
    return strncmp(s1, s2, n);
}

// Address range: 0x400c70 - 0x400c80
int32_t function_400c70(char * format, ...) {
    // 0x400c70
    return scanf(format);
}

// Address range: 0x400c80 - 0x400c90
void function_400c80(struct _IO_FILE * stream, char * buf) {
    // 0x400c80
    setbuf(stream, buf);
}

// Address range: 0x400c90 - 0x400ca0
int32_t function_400c90(int32_t main, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x400c90
    return __libc_start_main(main, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x400ca0 - 0x400cb0
int32_t function_400ca0(char * s) {
    // 0x400ca0
    return strlen(s);
}

// --------------- Dynamically Linked Functions ---------------

// int32_t __deregister_frame_info(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// int32_t __register_frame_info(void);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// int scanf(const char * restrict format, ...);
// void setbuf(FILE * restrict stream, char * restrict buf);
// size_t strlen(const char * s);
// int strncmp(const char * s1, const char * s2, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.3.0)
// Detected functions: 22
